from .board import board_routes
from .category import category_routes
from .comment import comment_routes
from .event import event_routes
from .invite import invite_routes
from .membership import membership_routes
from .post import post_routes
from .server import server_routes
from .user import user_routes
