FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY services/datastore/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/datastore/ ./datastore
COPY secrets/datastore /run/secrets/datastore
COPY secrets/cert /run/secrets/cert

EXPOSE 443

CMD ["uvicorn", "datastore.__init__:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/run/secrets/cert/key.pem", "--ssl-certfile", "/run/secrets/cert/cert.pem"]
