# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY datastore/requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY datastore/ datastore/

# Expose the port the app runs on
EXPOSE 443

# Command to run the FastAPI application
CMD ["uvicorn", "datastore:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/run/secrets/certs/key.pem", "--ssl-certfile", "/run/secrets/certs/cert.pem"]
