FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY services/datastore/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/datastore/ ./datastore
COPY secrets/datastore /run/secrets/datastore
COPY secrets/cert /run/secrets/cert

RUN export DATABASE_USER=$(cat /run/secrets/datastore/postgres_user.txt)
RUN export TEST_DATABASE_USER=$(cat /run/secrets/datastore/test_postgres_user.txt)
RUN echo "export DATABASE_USER=${DATABASE_USER}" >> /etc/profile.d/env.sh
RUN echo "export DATABASE_PASSWORD=${DATABASE_PASSWORD}" >> /etc/profile.d/env.sh

# Command to run the FastAPI application
CMD ["uvicorn", "datastore.__init__:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/run/secrets/cert/key.pem", "--ssl-certfile", "/run/secrets/cert/cert.pem"]

# Keep it open for debug
# CMD ["sleep", "1d"]